adestis_netbox_plugin_account_management/urls.py
from django.urls import path

from netbox.views.generic import ObjectChangeLogView
from adestis_netbox_plugin_account_management.models import *
from adestis_netbox_plugin_account_management.views import *

urlpatterns = (

    # System lists
    path('systems/', SystemListView.as_view(), name='system_list'),
    path('systems/add/', SystemEditView.as_view(), name='system_add'),
    path('systems/delete/', SystemBulkDeleteView.as_view(), name='system_bulk_delete'),
    path('systems/edit/', SystemBulkEditView.as_view(), name='system_bulk_edit'),
    path('systems/import/', SystemBulkImportView.as_view(), name='system_import'),
    path('systems/<int:pk>/', SystemView.as_view(), name='system'),
    path('systems/<int:pk>/edit/', SystemEditView.as_view(), name='system_edit'),
    path('systems/<int:pk>/delete/', SystemDeleteView.as_view(), name='system_delete'),
    path('systems/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='system_changelog', kwargs={
        'model': System
    }),

    # Login Credentials
    path('login-credentials/', LoginCredentialsListView.as_view(), name='logincredentials_list'),
    path('login-credentials/add/', LoginCredentialsEditView.as_view(), name='logincredentials_add'),
    path('login-credentials/delete/', LoginCredentialsBulkDeleteView.as_view(), name='logincredentials_bulk_delete'),
    path('login-credentials/edit/', LoginCredentialsBulkEditView.as_view(), name='logincredentials_bulk_edit'),
    path('login-credentials/import/', LoginCredentialsBulkImportView.as_view(), name='logincredentials_import'),
    path('login-credentials/<int:pk>/', LoginCredentialsView.as_view(), name='logincredentials'),
    path('login-credentials/<int:pk>/edit/', LoginCredentialsEditView.as_view(), name='logincredentials_edit'),
    path('login-credentials/<int:pk>/delete/', LoginCredentialsDeleteView.as_view(), name='logincredentials_delete'),
    path('login-credentials/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='logincredentials_changelog', kwargs={
        'model': LoginCredentials
    }),

)

adestis_netbox_plugin_account_management/models/login_credentials.py
from django.db import models
from django.urls import reverse

from adestis_netbox_plugin_account_management.models import *

from netbox.models import NetBoxModel
from utilities.choices import ChoiceSet
from tenancy.models import *

__all__ = (
    'LoginCredentialsStatusChoices',
    'LoginCredentials',
)


class LoginCredentialsStatusChoices(ChoiceSet):
    key = 'LoginCredentials.status'

    STATUS_OFFLINE = 'offline'
    STATUS_ACTIVE = 'active'
    STATUS_PLANNED = 'planned'
    STATUS_STAGED = 'staged'
    STATUS_FAILED = 'failed'
    STATUS_INVENTORY = 'inventory'
    STATUS_DECOMMISSIONING = 'decommissioning'

    CHOICES = [
        (STATUS_ACTIVE, 'Active', 'green'),
        (STATUS_OFFLINE, 'Offline', 'gray'),
        (STATUS_PLANNED, 'Planned', 'cyan'),
        (STATUS_STAGED, 'Staged', 'blue'),
        (STATUS_FAILED, 'Failed', 'red'),
        (STATUS_INVENTORY, 'Inventory', 'purple'),
        (STATUS_DECOMMISSIONING, 'Decommissioning', 'yellow'),
    ]


class LoginCredentials(NetBoxModel):
    system = models.ForeignKey(
        to=System,
        on_delete=models.PROTECT,
        null=True,
        verbose_name='System',
        help_text='System that is used by the Contact')

    logon_name = models.CharField(
        max_length=254,
        verbose_name='Logon name',
        help_text='Username of the user to login into system'
    )

    valid_from = models.DateField(
        null=True,
        blank=True,
        verbose_name='Valid from',
        help_text='Start of validity'
    )

    valid_to = models.DateField(
        null=True,
        blank=True,
        verbose_name='Valid to',
        help_text='End of validity'
    )

    login_credentials_status = models.CharField(
        max_length=50,
        choices=LoginCredentialsStatusChoices,
        verbose_name='Status',
        help_text='Status of the entry'
    )
       
    contact = models.ForeignKey(
        to='tenancy.Contact',
        on_delete=models.PROTECT,
        related_name='logincredentials_contact',
        null=True,
        verbose_name='Contact',
        help_text='Contact that uses the System'
    )

    comments = models.TextField(
        blank=True
    )

    class Meta:
        verbose_name_plural = "Login Credentials"
        verbose_name = 'Login Credentials'
        ordering = ('contact',)
        constraints = [
            models.UniqueConstraint(
                fields=['system', 'contact', 'logon_name'],
                name='%(app_label)s_%(class)s_unique_login_credentials'
            )
        ]

    def __str__(self):
        return self.logon_name

    def get_absolute_url(self):
        return reverse('plugins:adestis_netbox_plugin_account_management:logincredentials', args=[self.pk])

    def get_login_credentials_status_color(self):
        return LoginCredentialsStatusChoices.colors.get(self.login_credentials_status)

adestis_netbox_plugin_account_management/models/system.py
from django.db import models
from django.urls import reverse

from netbox.models import NetBoxModel
from utilities.choices import ChoiceSet

from virtualization.models import VirtualMachine, ClusterGroup, Cluster
from dcim.models import Device
from tenancy.models import *

from adestis_netbox_plugin_account_management.models import *

__all__ = (
    'SystemStatusChoices',
    'System',
)


class SystemStatusChoices(ChoiceSet):
    key = 'System.status'

    STATUS_OFFLINE = 'offline'
    STATUS_ACTIVE = 'active'
    STATUS_PLANNED = 'planned'
    STATUS_STAGED = 'staged'
    STATUS_FAILED = 'failed'
    STATUS_INVENTORY = 'inventory'
    STATUS_DECOMMISSIONING = 'decommissioning'

    CHOICES = [
        (STATUS_ACTIVE, 'Active', 'green'),
        (STATUS_OFFLINE, 'Offline', 'gray'),
        (STATUS_PLANNED, 'Planned', 'cyan'),
        (STATUS_STAGED, 'Staged', 'blue'),
        (STATUS_FAILED, 'Failed', 'red'),
        (STATUS_INVENTORY, 'Inventory', 'purple'),
        (STATUS_DECOMMISSIONING, 'Decommissioning', 'yellow'),
    ]


class System(NetBoxModel):
    name = models.CharField(
        max_length=130
    )

    system_url = models.CharField(
        max_length=2048,
        verbose_name='URL/Identification',
        blank=True
    )

    system_status = models.CharField(
        max_length=50,
        choices=SystemStatusChoices,
        verbose_name='Status'
    )

    comments = models.TextField(
        blank=True
    )
    
    device = models.ForeignKey(
        to='dcim.Device',
        on_delete=models.SET_NULL,
        related_name='system_device',
        blank=True,
        null=True
    )
    
    virtual_machine = models.ForeignKey(
        to='virtualization.VirtualMachine',
        on_delete=models.SET_NULL,
        related_name='system_virtual_machine',
        blank=True,
        null=True
    )
    
    cluster_group = models.ForeignKey(
        to='virtualization.ClusterGroup',
        on_delete=models.SET_NULL,
        related_name='system_cluster_group',
        blank=True,
        null=True
    )
    
    cluster = models.ForeignKey(
        to='virtualization.Cluster',
        on_delete=models.SET_NULL,
        related_name='system_cluster',
        blank=True,
        null=True
    )
    
    tenant = models.ForeignKey(
        to='tenancy.Tenant',
        on_delete=models.SET_NULL,
        related_name='system_tenant',
        blank=True,
        null=True
    )
    
    group = models.ForeignKey(
        to='tenancy.TenantGroup',
        on_delete=models.SET_NULL,
        related_name='system_tenantgroup',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name_plural = "Systems"
        verbose_name = 'System'
        ordering = ('name',)
        constraints = [
           models.UniqueConstraint(
               fields=['system_url'],
               name='%(app_label)s_%(class)s_unique_system_url'
           )
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('plugins:adestis_netbox_plugin_account_management:system', args=[self.pk])

    def get_system_status_color(self):
        return SystemStatusChoices.colors.get(self.system_status)

adestis_netbox_plugin_account_management/forms/login_credentials.py
from django import forms
from django.core.exceptions import ValidationError
from netbox.forms import NetBoxModelForm, NetBoxModelFilterSetForm, NetBoxModelBulkEditForm, NetBoxModelImportForm
from utilities.forms.fields import CommentField, DynamicModelChoiceField, DynamicModelMultipleChoiceField, CSVChoiceField, CSVModelChoiceField, TagFilterField
from utilities.forms.widgets import DatePicker
from adestis_netbox_plugin_account_management.models.login_credentials import LoginCredentials, LoginCredentialsStatusChoices
from adestis_netbox_plugin_account_management.models.system import System, SystemStatusChoices
from tenancy.models import Contact
from django.utils.translation import gettext_lazy as _
from utilities.forms.rendering import FieldSet


__all__ = (
    'LoginCredentialsForm',
    'LoginCredentialsFilterForm',
    'LoginCredentialsBulkEditForm',
    'LoginCredentialsCSVForm'
)


class LoginCredentialsForm(NetBoxModelForm):
    comments = CommentField()

    contact = DynamicModelChoiceField(
        queryset=Contact.objects.all(),
        required=True,
    )

    system = DynamicModelChoiceField(
        queryset=System.objects.all(),
        required=True,
    )

    fieldsets = (
        (None, ('logon_name', 'contact', 'system', 'login_credentials_status', 'tags')),
        ('Validity', ('valid_from', 'valid_to')),
    )  

    class Meta:
        model = LoginCredentials
        fields = ['logon_name', 'contact', 'system', 'valid_from', 'valid_to',
                  'login_credentials_status', 'comments', 'tags']
        widgets = {
            'valid_from': DatePicker(),
            'valid_to': DatePicker()
        }
        help_texts = {
            'logon_name': "Logon name",
        }

    def clean(self):
        super().clean()

        fieldsToValidate = [
            field for field in (
                'valid_from', 'valid_to'
            ) if self.cleaned_data[field]
        ]

        shouldValidate = len(fieldsToValidate)==2

        if shouldValidate == True:
            valid_from_data = self.cleaned_data["valid_from"]
            valid_to_data = self.cleaned_data["valid_to"]
            # Only do something if both fields are valid so far.
            if valid_to_data < valid_from_data:
                raise ValidationError(
                    "Invalid date range! Field 'Valid to' must be older than field 'Valid from'"
                )


class LoginCredentialsBulkEditForm(NetBoxModelBulkEditForm):
    pk = forms.ModelMultipleChoiceField(
        queryset=LoginCredentials.objects.all(),
        widget=forms.MultipleHiddenInput
    )
    
    system = DynamicModelChoiceField(
        queryset=System.objects.all(),
        required=False
    )
    
    contact = DynamicModelChoiceField(
        queryset=Contact.objects.all(),
        required=False
    )
    
    logon_name = forms.CharField(
        max_length=254,
        required=False
    )
    
    valid_from = forms.DateField(
        required=False
    )

    valid_to = forms.DateField(
        required=False
    )
    
    login_credentials_status = forms.ChoiceField(
        required=False,
        choices=LoginCredentialsStatusChoices,
    )

    model = LoginCredentials
    
    fieldsets = (
        (None, ('logon_name', 'contact', 'system', 'login_credentials_status')),
        ('Validity', ('valid_from', 'valid_to')),
    )  
    
    nullable_fields = [
       'valid_from', 'valid_to', 'add_tags', 'remove_tags'
    ]

class LoginCredentialsFilterForm(NetBoxModelFilterSetForm):
    model = LoginCredentials
    
    fieldsets = (
        (None, ('q', 'index', 'tag', 'contact', 'system', 'login_credentials_status')),
    )  

    index = forms.IntegerField(
        required=False
    )

    contact = DynamicModelMultipleChoiceField(
        queryset=Contact.objects.all(),
        required=False,
        null_option='None',
        to_field_name='name',
        label=_('Contact')
    )

    system = forms.ModelMultipleChoiceField(
        queryset=System.objects.all(),
        required=False
    )

    login_credentials_status = forms.MultipleChoiceField(
        choices = LoginCredentialsStatusChoices,
        required=False
    )
    
    tag = TagFilterField(model)
    
    
class LoginCredentialsCSVForm(NetBoxModelImportForm):
    
    system = CSVModelChoiceField(
        queryset=System.objects.all(),
        required=True,
        to_field_name='system_url',
        help_text='System URL'
    )
    
    contact = CSVModelChoiceField(
        queryset=Contact.objects.all(),
        required=True,
        to_field_name='email',
        help_text='Email address of the contact'
    )
    
    login_credentials_status = CSVChoiceField(
        choices=LoginCredentialsStatusChoices,
        help_text=_('Status'),
        required=True,
    )
        
    class Meta:
        model = LoginCredentials
        fields = ['system', 'contact', 'login_credentials_status', 'logon_name']
        default_return_url = 'plugins:adestis_netbox_plugin_account_management:logincredentials_list'

adestis_netbox_plugin_account_management/views/login_credentials.py
from netbox.views import generic
from adestis_netbox_plugin_account_management.forms import *
from adestis_netbox_plugin_account_management.models import *
from adestis_netbox_plugin_account_management.filtersets import *
from adestis_netbox_plugin_account_management.tables import *
from tenancy.models import Contact

from netbox.views import generic
from utilities.views import ViewTab, register_model_view

__all__ = (
    'LoginCredentialsView',
    'LoginCredentialsListView',
    'LoginCredentialsEditView',
    'LoginCredentialsDeleteView',
    'DeviceLoginCredentials',
    'LoginCredentialsBulkDeleteView',
    'LoginCredentialsBulkEditView',
    'LoginCredentialsBulkImportView'
)


class LoginCredentialsView(generic.ObjectView):
    queryset = LoginCredentials.objects.all()


class LoginCredentialsListView(generic.ObjectListView):
    queryset = LoginCredentials.objects.all()
    table = LoginCredentialsTable
    filterset = LoginCredentialsFilterSet
    filterset_form = LoginCredentialsFilterForm


class LoginCredentialsEditView(generic.ObjectEditView):
    queryset = LoginCredentials.objects.all()
    form = LoginCredentialsForm


class LoginCredentialsDeleteView(generic.ObjectDeleteView):
    queryset = LoginCredentials.objects.all()


@register_model_view(Contact, name='devicelogincredentials', path='login-credentials')
class DeviceLoginCredentials(generic.ObjectView):
    ...
    queryset = Contact.objects.all()
    template_name = "adestis_netbox_plugin_account_management/device_login_credentials_table.html"
    
    tab = ViewTab(
        label='Login Credentials',
        badge=None,
        hide_if_empty=False
    )

    def get_extra_context(self, request, instance):
        assets = LoginCredentials.objects.filter(contact=instance)
        table = LoginCredentialsTable(assets)
        data = {
            "table": table,
        }
        return data


class LoginCredentialsBulkDeleteView(generic.BulkDeleteView):
    queryset = LoginCredentials.objects.all()
    table = LoginCredentialsTable
    
    
class LoginCredentialsBulkEditView(generic.BulkEditView):
    queryset = LoginCredentials.objects.all()
    filterset = LoginCredentialsFilterSet
    table = LoginCredentialsTable
    form =  LoginCredentialsBulkEditForm
    

class LoginCredentialsBulkImportView(generic.BulkImportView):
    queryset = LoginCredentials.objects.all()
    model_form = LoginCredentialsCSVForm
    table = LoginCredentialsTable
    

adestis_netbox_plugin_account_management/views/system.py
from netbox.views import generic
from adestis_netbox_plugin_account_management.forms import *
from adestis_netbox_plugin_account_management.models import *
from adestis_netbox_plugin_account_management.filtersets import *
from adestis_netbox_plugin_account_management.tables import *

__all__ = (
    'SystemView',
    'SystemListView',
    'SystemEditView',
    'SystemDeleteView',
    'SystemBulkEditView',
    'SystemBulkDeleteView',
    'SystemBulkImportView'
)


class SystemView(generic.ObjectView):
    queryset = System.objects.all()

    def get_extra_context(self, request, instance):
        filtered_data = LoginCredentials.objects.filter(
            system=instance
        )
        
        systemview_filtered_table = LoginCredentialsTable(filtered_data, )

        return {
            'systemview_filtered_table': systemview_filtered_table,
        }


class SystemListView(generic.ObjectListView):
    queryset = System.objects.all()
    table = SystemTable
    filterset = SystemFilterSet
    filterset_form = SystemFilterForm


class SystemEditView(generic.ObjectEditView):
    queryset = System.objects.all()
    form = SystemForm


class SystemDeleteView(generic.ObjectDeleteView):
    queryset = System.objects.all()

class SystemBulkDeleteView(generic.BulkDeleteView):
    queryset = System.objects.all()
    table = SystemTable

class SystemBulkEditView(generic.BulkEditView):
    queryset = System.objects.all()
    filterset = SystemFilterSet
    table = SystemTable
    form =  SystemBulkEditForm
    
class SystemBulkImportView(generic.BulkImportView):
    queryset = System.objects.all()
    model_form = SystemCSVForm
    table = SystemTable

adestis_netbox_plugin_account_management/templates/adestis_netbox_plugin_account_management/device_login_credentials_table.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load static %}
{% load helpers %}
{% load plugins %}

{% load render_table from django_tables2 %}

{% block content %}
  <div class="card">
    <div class="card-body htmx-container table-responsive" id="object_list">
      {% include 'htmx/table.html' %}
    </div>
  </div>
{% endblock content %}

adestis_netbox_plugin_account_management/templates/adestis_netbox_plugin_account_management/logincredentials.html
{% extends 'generic/object.html' %}
{% load render_table from django_tables2 %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Login Credentials</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Logon name</th>
              <td>{{ object.logon_name |placeholder }}</td>
            </tr>
            <tr>
              <th scope="row">Contact</th>
              <td>
                {{ object.contact|linkify|placeholder }}
              </td>
            </tr>
            <tr>
              <th scope="row">System</th>
              <td>
                {{ object.system|linkify|placeholder }}
              </td>
            </tr>
            <tr>
              <th scope="row">Valid from</th>
              <td>
                {{ object.valid_from|placeholder }}
              </td>
            </tr>
            <tr>
              <th scope="row">Valid to</th>
              <td>
                {{ object.valid_to|placeholder }}
              </td>
            </tr>
            <tr>
              <th scope="row">Status</th>
              <td>{% badge object.get_login_credentials_status_display bg_color=object.get_login_credentials_status_color %}</td>
            </tr>
          </table>
        </div>
      </div>
      {% include 'inc/panels/custom_fields.html' %}
    </div>
    <div class="col col-md-6">
      {% include 'inc/panels/tags.html' %}
      {% include 'inc/panels/comments.html' %}
    </div>
  </div>
{% endblock content %}

adestis_netbox_plugin_account_management/templates/adestis_netbox_plugin_account_management/system.html
{% extends 'generic/object.html' %}
{% load render_table from django_tables2 %}

{% block content %}
  <div class="row my-3">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">System</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Name</th>
              <td>{{ object.name }}</td>
            </tr>
            <tr>
              <th scope="row">URL / Identification</th>
              <td>{{ object.system_url }}</td>
            </tr>
            <tr>
              <th scope="row">Status</th>
              <td>{% badge object.get_system_status_display bg_color=object.get_system_status_color %}</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">Computing</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Group</th>
              <td>
                {{ object.group|linkify|placeholder }}
              </td>
            </tr>
            <tr>
              <th scope="row">Tenant</th>
              <td>
                {{ object.tenant|linkify|placeholder }}
              </td>
            </tr>
            <tr>
              <th scope="row">Cluster Group</th>
              <td>
                {{ object.cluster_group|linkify|placeholder }}
              </td>
            </tr>
            <tr>
              <th scope="row">Cluster</th>
              <td>
                {{ object.cluster|linkify|placeholder }}
              </td>
            </tr>
            <tr>
              <th scope="row">Device</th>
              <td>
                {{ object.device|linkify|placeholder }}
              </td>
            </tr>
            <tr>
              <th scope="row">Virtual Machine</th>
              <td>
                {{ object.virtual_machine|linkify|placeholder }}
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
    <div class="row my-3">
      <div class="col col-md-6">
        {% include 'inc/panels/custom_fields.html' %}
        {% include 'inc/panels/tags.html' %}
        {% include 'inc/panels/comments.html' %}
      </div>
    </div>

  </div>
  <div class="row mb-3">
    <div class="col col-md-12">
      <div class="card">
        <h5 class="card-header">Connected Systems</h5>
        <div class="card-body table-responsive">
          {% render_table systemview_filtered_table 'inc/table.html' %}
          {% include 'inc/paginator.html' with paginator=systemview_filtered_table.paginator page=systemview_filtered_table.page %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}